/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caware;

import javax.swing.JInternalFrame;

/**
 *
 * @author 12p10
 */
public class HomeForm extends javax.swing.JFrame {

    private DBHandler dbHandler;

    /**
     * Creates new form HomeForm
     */
    public HomeForm(DBHandler db) {
        initComponents();

        //assign database
        dbHandler = db;

        //clean-up UI layout
        
        detailsInternalFrame.setSize(250, 350);
        detailsPanel.setSize(detailsInternalFrame.getSize());
        detailsPanel.setDB(dbHandler);
        detailsPanel.setParent(detailsInternalFrame);
        detailsPanel.setNextFrame(quesInternalFrame);
        detailsInternalFrame.setVisible(false);
        
        quesPanel.setSize(quesInternalFrame.getSize());
        quesPanel.setDB(dbHandler);
        quesPanel.setParent(quesInternalFrame);
        quesPanel.setLanguage(1);
        quesPanel.initiate();
        quesInternalFrame.setVisible(false);
        
        //language settings - group radiobuttons
        btnGroupLanguage.add(rbHindi);
        btnGroupLanguage.add(rbEnglish);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupLanguage = new javax.swing.ButtonGroup();
        DesktopPane = new javax.swing.JDesktopPane();
        detailsInternalFrame = new javax.swing.JInternalFrame();
        detailsPanel = new caware.InfoPanel();
        quesInternalFrame = new javax.swing.JInternalFrame();
        quesPanel = new caware.QuestionPanel();
        MainMenu = new javax.swing.JMenuBar();
        menuSurvey = new javax.swing.JMenu();
        menuStartNew = new javax.swing.JMenuItem();
        menuResults = new javax.swing.JMenu();
        menuSettings = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        rbHindi = new javax.swing.JRadioButtonMenuItem();
        rbEnglish = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C-Aware");
        setMaximumSize(new java.awt.Dimension(1368, 720));
        setMinimumSize(new java.awt.Dimension(1368, 720));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1368, 700));
        setResizable(false);

        DesktopPane.setMaximumSize(new java.awt.Dimension(1368, 720));
        DesktopPane.setMinimumSize(new java.awt.Dimension(1368, 720));

        detailsInternalFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailsInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        detailsInternalFrame.setTitle("Survey - Step 1");
        detailsInternalFrame.setToolTipText("Survey - Step 1");
        detailsInternalFrame.setMaximumSize(new java.awt.Dimension(250, 350));
        detailsInternalFrame.setMinimumSize(new java.awt.Dimension(250, 350));
        detailsInternalFrame.setPreferredSize(new java.awt.Dimension(250, 350));
        detailsInternalFrame.setVisible(true);

        detailsPanel.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Basic Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        detailsPanel.setMaximumSize(new java.awt.Dimension(250, 350));
        detailsPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout detailsInternalFrameLayout = new javax.swing.GroupLayout(detailsInternalFrame.getContentPane());
        detailsInternalFrame.getContentPane().setLayout(detailsInternalFrameLayout);
        detailsInternalFrameLayout.setHorizontalGroup(
            detailsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        detailsInternalFrameLayout.setVerticalGroup(
            detailsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsInternalFrameLayout.createSequentialGroup()
                .addComponent(detailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        quesInternalFrame.setTitle("Survey - Step 2");
        quesInternalFrame.setVisible(true);

        javax.swing.GroupLayout quesInternalFrameLayout = new javax.swing.GroupLayout(quesInternalFrame.getContentPane());
        quesInternalFrame.getContentPane().setLayout(quesInternalFrameLayout);
        quesInternalFrameLayout.setHorizontalGroup(
            quesInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quesInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quesInternalFrameLayout.setVerticalGroup(
            quesInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quesInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(detailsInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(quesInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quesInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detailsInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        DesktopPane.setLayer(detailsInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopPane.setLayer(quesInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menuSurvey.setText("Survey");
        menuSurvey.setName(""); // NOI18N

        menuStartNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuStartNew.setText("Start New Record");
        menuStartNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStartNewActionPerformed(evt);
            }
        });
        menuSurvey.add(menuStartNew);

        MainMenu.add(menuSurvey);

        menuResults.setText("Results");
        MainMenu.add(menuResults);

        menuSettings.setText("Settings");
        menuSettings.add(jSeparator1);

        rbHindi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        rbHindi.setText("Hindi");
        rbHindi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHindiActionPerformed(evt);
            }
        });
        menuSettings.add(rbHindi);

        rbEnglish.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        rbEnglish.setSelected(true);
        rbEnglish.setText("English");
        rbEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEnglishActionPerformed(evt);
            }
        });
        menuSettings.add(rbEnglish);

        MainMenu.add(menuSettings);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbHindiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHindiActionPerformed
        
        quesPanel.setLanguage(0);
        
    }//GEN-LAST:event_rbHindiActionPerformed

    private void menuStartNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStartNewActionPerformed

        //detailsInternalFrame.show();
        detailsInternalFrame.setVisible(true);
        
        System.out.println("opened first frame");

    }//GEN-LAST:event_menuStartNewActionPerformed

    private void rbEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEnglishActionPerformed
        
        quesPanel.setLanguage(1);
        
    }//GEN-LAST:event_rbEnglishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.ButtonGroup btnGroupLanguage;
    private javax.swing.JInternalFrame detailsInternalFrame;
    private caware.InfoPanel detailsPanel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuResults;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenuItem menuStartNew;
    private javax.swing.JMenu menuSurvey;
    private javax.swing.JInternalFrame quesInternalFrame;
    private caware.QuestionPanel quesPanel;
    private javax.swing.JRadioButtonMenuItem rbEnglish;
    private javax.swing.JRadioButtonMenuItem rbHindi;
    // End of variables declaration//GEN-END:variables
}
