/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package caware;

import javax.swing.JInternalFrame;

/**
 *
 * @author 12p10
 */
public class HomeForm extends javax.swing.JFrame {

    private DBHandler dbHandler;
        
    /**
     * Creates new form HomeForm
     */
    public HomeForm(DBHandler db) {
        initComponents();
        
        dbHandler = db;
        DesktopPane.setSize(super.getSize());
        quesInternalFrame.setSize(250, 350);
        quesPanel.setSize(quesInternalFrame.getSize());
        quesPanel.setDB(dbHandler);
        quesPanel.setParent(quesInternalFrame);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        quesInternalFrame = new javax.swing.JInternalFrame();
        quesPanel = new caware.InfoPanel();
        MainMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quesInternalFrame.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quesInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        quesInternalFrame.setMaximumSize(new java.awt.Dimension(250, 350));
        quesInternalFrame.setMinimumSize(new java.awt.Dimension(250, 350));
        quesInternalFrame.setPreferredSize(new java.awt.Dimension(250, 350));
        quesInternalFrame.setVisible(true);

        quesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Basic Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        quesPanel.setMaximumSize(new java.awt.Dimension(250, 350));
        quesPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout quesInternalFrameLayout = new javax.swing.GroupLayout(quesInternalFrame.getContentPane());
        quesInternalFrame.getContentPane().setLayout(quesInternalFrameLayout);
        quesInternalFrameLayout.setHorizontalGroup(
            quesInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quesPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        quesInternalFrameLayout.setVerticalGroup(
            quesInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quesInternalFrameLayout.createSequentialGroup()
                .addComponent(quesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(quesInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(quesInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        DesktopPane.setLayer(quesInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MainMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Survey");
        jMenu1.setName(""); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Start New Basic Details");
        jMenu1.add(jMenuItem1);

        MainMenu.add(jMenu1);

        jMenu2.setText("Results");
        MainMenu.add(jMenu2);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JInternalFrame quesInternalFrame;
    private caware.InfoPanel quesPanel;
    // End of variables declaration//GEN-END:variables
}
