/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caware;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 12p10
 */
public class QuestionPanel extends javax.swing.JPanel {

    private DBHandler dbHandler;
    private String[] responses;
    private JInternalFrame parentFrame;
    private QuestionFeeder questionFeeder;
    private int questionIndex; //zero-based index

    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
        responses = new String[24];
        questionFeeder = new QuestionFeeder();

    }

    public void setParent(JInternalFrame parent) {
        parentFrame = parent;
    }

    public void setDB(DBHandler db) {

        dbHandler = db;
        System.out.println("db set");
    }

    public void setLanguage(int i) {

        questionFeeder.setLanguage(i);

    }

    public void initiate() {

        lblQuestion.setText(questionFeeder.nextQuestion());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Survey Questions"));

        lblQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("jLabel1");
        lblQuestion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuestion.setMaximumSize(new java.awt.Dimension(50, 100));
        lblQuestion.setMinimumSize(new java.awt.Dimension(50, 100));
        lblQuestion.setPreferredSize(new java.awt.Dimension(50, 100));

        btnYes.setBackground(new java.awt.Color(0, 102, 51));
        btnYes.setForeground(new java.awt.Color(255, 255, 255));
        btnYes.setText("Yes");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        btnNo.setBackground(new java.awt.Color(204, 0, 0));
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        jProgressBar1.setMaximum(24);
        jProgressBar1.setMinimum(1);
        jProgressBar1.setOrientation(1);
        jProgressBar1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnYes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNo)
                            .addComponent(btnYes)))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed

        responses[questionIndex] = "1";
        if (questionIndex == 23) {
            btnYes.setEnabled(false);
            btnNo.setEnabled(false);
            saveToDB();
        } else {
            lblQuestion.setText(questionFeeder.nextQuestion());
        }
        questionIndex++;

    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        
        jProgressBar1.setValue(questionIndex);
        responses[questionIndex] = "0";
        if (questionIndex == 23) {
            btnYes.setEnabled(false);
            btnNo.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Survey complete! Thank you for your time.");
            saveToDB();
        } else {
             lblQuestion.setText("<html>" + questionFeeder.nextQuestion() + "<html>");
        }
        questionIndex++;

    }//GEN-LAST:event_btnNoActionPerformed

    private void saveToDB() {

        dbHandler.addQuestionResponse(responses);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
