/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caware;

import javax.swing.JInternalFrame;

/**
 *
 * @author 12p10
 */
public class QuestionPanel extends javax.swing.JPanel {

    private DBHandler dbHandler;
    private String[] responses;
    private JInternalFrame parentFrame;
    private QuestionFeeder questionFeeder;
    private int questionIndex; //zero-based index
    
    /**
     * Creates new form QuestionPanel
     */
    public QuestionPanel() {
        initComponents();
        responses = new String[24];
        questionFeeder = new QuestionFeeder();
        
    }

    public void setParent(JInternalFrame parent) {
        parentFrame = parent;
    }

    public void setDB(DBHandler db) {

        dbHandler = db;
        System.out.println("db set");
    }

    public void setLanguage(int i){
    
        questionFeeder.setLanguage(i);
        
    }
    
    public void initiate(){
    
        lblQuestion.setText(questionFeeder.nextQuestion());
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Survey Questions"));

        lblQuestion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("jLabel1");

        btnYes.setBackground(new java.awt.Color(0, 102, 51));
        btnYes.setForeground(new java.awt.Color(255, 255, 255));
        btnYes.setText("Yes");

        btnNo.setBackground(new java.awt.Color(204, 0, 0));
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addComponent(btnYes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNo)
                    .addComponent(btnYes))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
